#server:
#  port: 8080
#
spring:
#
  datasource:
    url: jdbc:h2:mem:expert
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#    open-in-view: false
#
  h2:
    console:
      enabled: true
      path: /h2-console